<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE shakemap-data [
<!ELEMENT shakemap-data (earthquake,stationlist)>
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  netid		CDATA			#REQUIRED
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ELEMENT  earthquake EMPTY>
<!ATTLIST earthquake
  id 		ID	#REQUIRED
  lat		CDATA	#REQUIRED
  lon		CDATA	#REQUIRED
  mag		CDATA	#REQUIRED
  year          CDATA   #REQUIRED
  month         CDATA   #REQUIRED
  day           CDATA   #REQUIRED
  hour          CDATA   #REQUIRED
  minute        CDATA   #REQUIRED
  second        CDATA   #REQUIRED
  timezone      CDATA   #REQUIRED
  depth		CDATA	#REQUIRED
  type		CDATA	#REQUIRED
  locstring	CDATA	#REQUIRED
  pga		CDATA   #REQUIRED
  pgv		CDATA   #REQUIRED
  sp03		CDATA   #REQUIRED
  sp10		CDATA   #REQUIRED
  sp30		CDATA   #REQUIRED
  created	CDATA	#REQUIRED
>
]>
<shakemap-data code_version="3.5" map_version="1">
<earthquake id="19900716072634" lat="15.75100" lon="121.19000" mag="7.7" year="1990" month="7" day="16" hour="7" minute="26" second="34" timezone="GMT" depth="20.0" network="us" locstring="Luzon, Philippines" created="1485474746" />
<stationlist created="1485474746">
<station code="OBS_1" name="Baguio" insttype="Observed" lat="16.41" lon="120.59" dist="33.833087" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="57.90" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="94.43" flag="0" />
<psa10 value="80.10" flag="0" />
<psa30 value="14.77" flag="0" />
</comp>
</station>
<station code="OBS_2" name="Bayombong" insttype="Observed" lat="16.49" lon="121.15" dist="27.649042" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="61.21" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="97.23" flag="0" />
<psa10 value="77.41" flag="0" />
<psa30 value="14.22" flag="0" />
</comp>
</station>
<station code="OBS_3" name="Santa Fe" insttype="Observed" lat="16.22" lon="120.90" dist="4.629075" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="81.02" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="112.67" flag="0" />
<psa10 value="65.19" flag="0" />
<psa30 value="11.73" flag="0" />
</comp>
</station>
<station code="OBS_4" name="San Jose" insttype="Observed" lat="15.79" lon="120.99" dist="13.599483" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="74.44" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="107.76" flag="0" />
<psa10 value="68.67" flag="0" />
<psa30 value="12.43" flag="0" />
</comp>
</station>
<station code="OBS_5" name="Bitulok" insttype="Observed" lat="15.48" lon="121.31" dist="10.425148" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="80.10" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="111.99" flag="0" />
<psa10 value="65.65" flag="0" />
<psa30 value="11.82" flag="0" />
</comp>
</station>
<station code="OBS_6" name="Calipahan" insttype="Observed" lat="15.56" lon="120.96" dist="32.813079" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="58.39" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="94.85" flag="0" />
<psa10 value="79.69" flag="0" />
<psa30 value="14.68" flag="0" />
</comp>
</station>
<station code="OBS_7" name="Manila" insttype="Observed" lat="14.61" lon="120.97" dist="108.061843" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.0">
<comp name="DERIVED">
<pga value="22.56" flag="0" />
<pgv value="27.02" flag="0" />
<psa03 value="45.76" flag="0" />
<psa10 value="44.06" flag="0" />
<psa30 value="8.56" flag="0" />
</comp>
</station>
<station code="OBS_8" name="San Fernando" insttype="Observed" lat="16.62" lon="120.32" dist="67.400375" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.0">
<comp name="DERIVED">
<pga value="25.70" flag="0" />
<pgv value="27.02" flag="0" />
<psa03 value="49.00" flag="0" />
<psa10 value="40.68" flag="0" />
<psa30 value="7.83" flag="0" />
</comp>
</station>
<station code="OBS_9" name="Unknown" insttype="Observed" lat="15.77" lon="121.15" dist="2.174652" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="81.02" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="112.67" flag="0" />
<psa10 value="65.19" flag="0" />
<psa30 value="11.73" flag="0" />
</comp>
</station>
<station code="OBS_10" name="Agoo" insttype="Observed" lat="16.33" lon="120.36" dist="57.663511" source="Rantucci (1994)" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="49.98" flag="0" />
<pgv value="55.99" flag="0" />
<psa03 value="87.40" flag="0" />
<psa10 value="87.65" flag="0" />
<psa30 value="16.34" flag="0" />
</comp>
</station>

</stationlist>
</shakemap-data>
